spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://284a20274a14ed0b82b51acf4a46217a@o4507290482311168.ingest.de.sentry.io/4507290746552400
  traces-sample-rate: 1.0
